namespace HermesProxy.World.Enums.V1_14_1_40688;

public enum ConversationDynamicField
{
	CONVERSATION_DYNAMIC_FIELD_ACTORS = 0,
	CONVERSATION_DYNAMIC_FIELD_LINES = 1,
	CONVERSATION_DYNAMIC_END = 2
}
