namespace HermesProxy.World.Enums.V1_14_1_40688;

public enum UnitDynamicField
{
	UNIT_DYNAMIC_FIELD_PASSIVE_SPELLS = 0,
	UNIT_DYNAMIC_FIELD_WORLD_EFFECTS = 1,
	UNIT_DYNAMIC_FIELD_CHANNEL_OBJECTS = 2,
	UNIT_DYNAMIC_END = 3
}
