namespace HermesProxy.World.Enums.V1_14_0_40237;

public enum ActivePlayerDynamicField
{
	ACTIVE_PLAYER_DYNAMIC_FIELD_RESEARCH = 4,
	ACTIVE_PLAYER_DYNAMIC_FIELD_RESEARCH_SITES = 5,
	ACTIVE_PLAYER_DYNAMIC_FIELD_RESEARCH_SITE_PROGRESS = 6,
	ACTIVE_PLAYER_DYNAMIC_FIELD_DAILY_QUESTS_COMPLETED = 7,
	ACTIVE_PLAYER_DYNAMIC_FIELD_AVAILABLE_QUEST_LINE_X_QUEST_IDS = 8,
	ACTIVE_PLAYER_DYNAMIC_FIELD_HEIRLOOMS = 9,
	ACTIVE_PLAYER_DYNAMIC_FIELD_HEIRLOOM_FLAGS = 10,
	ACTIVE_PLAYER_DYNAMIC_FIELD_TOYS = 11,
	ACTIVE_PLAYER_DYNAMIC_FIELD_TRANSMOG = 12,
	ACTIVE_PLAYER_DYNAMIC_FIELD_CONDITIONAL_TRANSMOG = 13,
	ACTIVE_PLAYER_DYNAMIC_FIELD_SELF_RES_SPELLS = 14,
	ACTIVE_PLAYER_DYNAMIC_FIELD_CHARACTER_RESTRICTIONS = 15,
	ACTIVE_PLAYER_DYNAMIC_FIELD_SPELL_FLAT_MOD_BY_LABEL = 16,
	ACTIVE_PLAYER_DYNAMIC_FIELD_SPELL_PCT_MOD_BY_LABEL = 17,
	ACTIVE_PLAYER_DYNAMIC_END = 18
}
