namespace HermesProxy.World.Enums.V1_14_0_40237;

public enum ConversationDynamicField
{
	CONVERSATION_DYNAMIC_FIELD_ACTORS = 0,
	CONVERSATION_DYNAMIC_FIELD_LINES = 1,
	CONVERSATION_DYNAMIC_END = 2
}
