import re

# Read WPP opcodes
with open('f:/Ampps/HermesProxy-master/tmp_certs/wpp_opcodes_343.cs', 'r') as f:
    wpp = f.read()
wpp_opcodes = {}
for m in re.finditer(r'Opcode\.(\w+),\s*(0x[0-9A-Fa-f]+)', wpp):
    wpp_opcodes[m.group(1)] = m.group(2)

# Read current file
with open('f:/Ampps/HermesProxy-master/HermesProxy/World/Enums/V3_4_3_54261/Opcode.cs', 'r') as f:
    hermes = f.read()

# Name mappings: HermesProxy -> WowPacketParser
name_map = {
    'CMSG_CHAR_CREATE': 'CMSG_CREATE_CHARACTER',
    'CMSG_CHAR_ENUM': 'CMSG_ENUM_CHARACTERS',
    'CMSG_CHAR_RENAME': 'CMSG_CHARACTER_RENAME_REQUEST',
    'CMSG_CREATURE_QUERY': 'CMSG_QUERY_CREATURE',
    'CMSG_DUEL_ACCEPTED': 'CMSG_DUEL_RESPONSE',
    'CMSG_GAMEOBJECT_QUERY': 'CMSG_QUERY_GAME_OBJECT',
    'CMSG_GAMEOBJ_REPORT_USE': 'CMSG_GAME_OBJ_REPORT_USE',
    'CMSG_GAMEOBJ_USE': 'CMSG_GAME_OBJ_USE',
    'CMSG_GET_MAIL_LIST': 'CMSG_MAIL_GET_LIST',
    'CMSG_GOSSIP_HELLO': 'CMSG_HELLO',
    'CMSG_GROUP_ACCEPT': 'CMSG_PARTY_INVITE_RESPONSE',
    'CMSG_CLOSE_INTERACT_OBJECT': 'CMSG_CLOSE_INTERACTION',
    'CMSG_FORCE_MOVE_ROOT_ACK': 'CMSG_MOVE_FORCE_ROOT_ACK',
    'CMSG_FORCE_MOVE_UNROOT_ACK': 'CMSG_MOVE_FORCE_UNROOT_ACK',
    'CMSG_GROUP_DISBAND': 'CMSG_LEAVE_GROUP',
    'CMSG_GROUP_INVITE': 'CMSG_PARTY_INVITE',
    'CMSG_GROUP_RAID_CONVERT': 'CMSG_CONVERT_RAID',
    'CMSG_GROUP_SET_LEADER': 'CMSG_SET_PARTY_LEADER',
    'CMSG_GROUP_UNINVITE': 'CMSG_PARTY_UNINVITE',
    'CMSG_GUILD_QUERY': 'CMSG_QUERY_GUILD_INFO',
    'CMSG_GUILD_ACCEPT': 'CMSG_ACCEPT_GUILD_INVITE',
    'CMSG_GUILD_DECLINE': 'CMSG_DECLINE_GUILD_INVITES',
    'CMSG_GUILD_DISBAND': 'CMSG_GUILD_DELETE',
    'CMSG_GUILD_INFO': 'CMSG_QUERY_GUILD_INFO',
    'CMSG_GUILD_INVITE': 'CMSG_GUILD_INVITE_BY_NAME',
    'CMSG_GUILD_MOTD': 'CMSG_GUILD_UPDATE_MOTD_TEXT',
    'CMSG_GUILD_RANK': 'CMSG_GUILD_SET_RANK_PERMISSIONS',
    'CMSG_GUILD_REMOVE': 'CMSG_GUILD_OFFICER_REMOVE_MEMBER',
    'CMSG_GUILD_ROSTER': 'CMSG_REQUEST_GUILD_PARTY_STATE',
    'CMSG_GUILD_SET_NOTE': 'CMSG_GUILD_SET_MEMBER_NOTE',
    'CMSG_ITEM_QUERY': 'CMSG_ITEM_QUERY_SINGLE',
    'CMSG_JOIN_CHANNEL': 'CMSG_CHAT_JOIN_CHANNEL',
    'CMSG_LEARN_TALENT': 'CMSG_LEARN_TALENTS',
    'CMSG_LEAVE_CHANNEL': 'CMSG_CHAT_LEAVE_CHANNEL',
    'CMSG_LOOT': 'CMSG_LOOT_UNIT',
    'CMSG_NPC_TEXT_QUERY': 'CMSG_QUERY_NPC_TEXT',
    'CMSG_PAGE_TEXT_QUERY': 'CMSG_QUERY_PAGE_TEXT',
    'CMSG_PET_NAME_QUERY': 'CMSG_QUERY_PET_NAME',
    'CMSG_QUEST_QUERY': 'CMSG_QUERY_QUEST_INFO',
    'CMSG_CHANNEL_SILENCE_ALL': 'CMSG_CHAT_CHANNEL_SILENCE_ALL',
    'CMSG_CHANNEL_UNSILENCE_ALL': 'CMSG_CHAT_CHANNEL_UNSILENCE_ALL',
    'CMSG_CLEAR_CHANNEL_WATCH': 'CMSG_CHAT_CHANNEL_DECLINE_INVITE',
    'CMSG_DUEL_CANCELLED': 'CMSG_DUEL_RESPONSE',
    'CMSG_DUEL_PROPOSED': 'CMSG_CAST_SPELL',
    'CMSG_EQUIP_ERROR_TOAST': 'CMSG_ADDON_LIST',
    'SMSG_ACTION_BUTTONS': 'SMSG_UPDATE_ACTION_BUTTONS',
    'SMSG_AUTH_RESPONSE': 'SMSG_AUTH_RESPONSE',
    'SMSG_CHAR_ENUM': 'SMSG_ENUM_CHARACTERS_RESULT',
    'SMSG_CHAR_CREATE': 'SMSG_CREATE_CHAR',
    'SMSG_CREATURE_QUERY_RESPONSE': 'SMSG_QUERY_CREATURE_RESPONSE',
    'SMSG_GAMEOBJECT_QUERY_RESPONSE': 'SMSG_QUERY_GAME_OBJECT_RESPONSE',
    'SMSG_GROUP_LIST': 'SMSG_PARTY_UPDATE',
    'SMSG_GUILD_QUERY_RESPONSE': 'SMSG_QUERY_GUILD_INFO_RESPONSE',
    'SMSG_GUILD_EVENT': 'SMSG_GUILD_EVENT_PRESENCE_CHANGE',
    'SMSG_INITIAL_SPELLS': 'SMSG_SEND_KNOWN_SPELLS',
    'SMSG_ITEM_QUERY_RESPONSE': 'SMSG_ITEM_QUERY_SINGLE_RESPONSE',
    'SMSG_MESSAGECHAT': 'SMSG_CHAT',
    'SMSG_NPC_TEXT_UPDATE': 'SMSG_QUERY_NPC_TEXT_RESPONSE',
    'SMSG_PAGE_TEXT_QUERY_RESPONSE': 'SMSG_QUERY_PAGE_TEXT_RESPONSE',
    'SMSG_PET_NAME_QUERY_RESPONSE': 'SMSG_QUERY_PET_NAME_RESPONSE',
    'SMSG_QUEST_QUERY_RESPONSE': 'SMSG_QUERY_QUEST_INFO_RESPONSE',
    'SMSG_CHANNEL_LIST': 'SMSG_CHAT_CHANNEL_LIST',
    'SMSG_CHANNEL_NOTIFY': 'SMSG_CHAT_CHANNEL_NOTIFY',
    'SMSG_DUEL_WINNER': 'SMSG_DUEL_WINNER',
    'SMSG_DUEL_COMPLETE': 'SMSG_DUEL_COMPLETE',
    'SMSG_DUEL_REQUESTED': 'SMSG_DUEL_REQUESTED',
    'SMSG_FORCE_MOVE_ROOT': 'SMSG_MOVE_ROOT',
    'SMSG_FORCE_MOVE_UNROOT': 'SMSG_MOVE_UNROOT',
    'SMSG_GUILD_COMMAND_RESULT': 'SMSG_GUILD_COMMAND_RESULT',
    'SMSG_GUILD_INVITE': 'SMSG_GUILD_INVITE',
    'SMSG_LEARNED_SPELLS': 'SMSG_LEARNED_SPELLS',
    'SMSG_LOG_XP_GAIN': 'SMSG_LOG_XP_GAIN',
    'SMSG_LOOT_RESPONSE': 'SMSG_LOOT_RESPONSE',
    'SMSG_LOOT_RELEASE': 'SMSG_LOOT_RELEASE',
    'SMSG_MAIL_LIST_RESULT': 'SMSG_MAIL_LIST_RESULT',
    'SMSG_MAIL_SEND_RESULT': 'SMSG_SEND_MAIL_RESULT',
    'SMSG_MOVE_KNOCK_BACK': 'SMSG_MOVE_KNOCK_BACK',
    'SMSG_MOVE_TELEPORT': 'SMSG_MOVE_TELEPORT',
    'SMSG_NAME_QUERY_RESPONSE': 'SMSG_QUERY_PLAYER_NAMES_RESPONSE',
    'SMSG_NEW_WORLD': 'SMSG_NEW_WORLD',
    'SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA': 'SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA',
    'SMSG_PARTY_INVITE': 'SMSG_PARTY_INVITE',
    'SMSG_PARTY_MEMBER_STATS': 'SMSG_PARTY_MEMBER_FULL_STATE',
    'SMSG_PET_SPELLS': 'SMSG_PET_SPELLS_MESSAGE',
    'SMSG_PLAYED_TIME': 'SMSG_PLAYED_TIME',
    'SMSG_POWER_UPDATE': 'SMSG_POWER_UPDATE',
    'SMSG_QUEST_GIVER_OFFER_REWARD': 'SMSG_QUEST_GIVER_OFFER_REWARD_MESSAGE',
    'SMSG_QUEST_GIVER_QUEST_DETAILS': 'SMSG_QUEST_GIVER_QUEST_DETAILS',
    'SMSG_QUEST_GIVER_QUEST_LIST': 'SMSG_QUEST_GIVER_QUEST_LIST_MESSAGE',
    'SMSG_QUEST_GIVER_STATUS': 'SMSG_QUEST_GIVER_STATUS',
    'SMSG_QUEST_GIVER_STATUS_MULTIPLE': 'SMSG_QUEST_GIVER_STATUS_MULTIPLE',
    'SMSG_SELL_RESPONSE': 'SMSG_SELL_RESPONSE',
    'SMSG_SEND_MAIL_RESULT': 'SMSG_SEND_MAIL_RESULT',
    'SMSG_SET_FLAT_SPELL_MODIFIER': 'SMSG_SET_FLAT_SPELL_MODIFIER',
    'SMSG_SET_PCT_SPELL_MODIFIER': 'SMSG_SET_PCT_SPELL_MODIFIER',
    'SMSG_SPELL_FAILURE': 'SMSG_SPELL_FAILURE',
    'SMSG_SPELL_GO': 'SMSG_SPELL_GO',
    'SMSG_SPELL_START': 'SMSG_SPELL_START',
    'SMSG_STAND_STATE_UPDATE': 'SMSG_STAND_STATE_UPDATE',
    'SMSG_TALENT_UPDATE': 'SMSG_UPDATE_TALENT_DATA',
    'SMSG_TAXI_NODE_STATUS': 'SMSG_TAXI_NODE_STATUS',
    'SMSG_TRANSFER_PENDING': 'SMSG_TRANSFER_PENDING',
    'SMSG_TRAINER_LIST': 'SMSG_TRAINER_LIST',
    'SMSG_VENDOR_INVENTORY': 'SMSG_LIST_INVENTORY',
    'SMSG_WEATHER': 'SMSG_WEATHER',
}

matched = 0
for hermes_name, wpp_name in name_map.items():
    if wpp_name in wpp_opcodes:
        pattern = rf'({re.escape(hermes_name)}\s*=\s*)0x0000(,?\s*//\s*TODO)?'
        new_hermes = re.sub(pattern, rf'\g<1>{wpp_opcodes[wpp_name]},', hermes, count=1)
        if new_hermes != hermes:
            matched += 1
            hermes = new_hermes

remaining_zeros = len(re.findall(r'=\s*0x0000', hermes))
print(f'Additional matched: {matched}')
print(f'Opcodes still at 0x0000: {remaining_zeros}')

# Show remaining zeros
remaining = re.findall(r'(\w+)\s*=\s*0x0000', hermes)
print(f'Remaining unmatched: {remaining[:40]}')

with open('f:/Ampps/HermesProxy-master/HermesProxy/World/Enums/V3_4_3_54261/Opcode.cs', 'w') as f:
    f.write(hermes)
