namespace HermesProxy.World.Enums;

public enum ActivePlayerDynamicField
{
	ACTIVE_PLAYER_DYNAMIC_END = 0,
	ACTIVE_PLAYER_DYNAMIC_FIELD_AVAILABLE_QUEST_LINE_X_QUEST_ID = 1,
	ACTIVE_PLAYER_DYNAMIC_FIELD_CHARACTER_RESTRICTIONS = 2,
	ACTIVE_PLAYER_DYNAMIC_FIELD_CONDITIONAL_TRANSMOG = 3,
	ACTIVE_PLAYER_DYNAMIC_FIELD_DAILY_QUESTS = 4,
	ACTIVE_PLAYER_DYNAMIC_FIELD_HEIRLOOM_FLAGS = 5,
	ACTIVE_PLAYER_DYNAMIC_FIELD_HEIRLOOMS = 6,
	ACTIVE_PLAYER_DYNAMIC_FIELD_RESEARCH_SITE_PROGRESS = 7,
	ACTIVE_PLAYER_DYNAMIC_FIELD_RESERACH = 8,
	ACTIVE_PLAYER_DYNAMIC_FIELD_RESERACH_SITE = 9,
	ACTIVE_PLAYER_DYNAMIC_FIELD_SELF_RES_SPELLS = 10,
	ACTIVE_PLAYER_DYNAMIC_FIELD_SPELL_FLAT_MOD_BY_LABEL = 11,
	ACTIVE_PLAYER_DYNAMIC_FIELD_SPELL_PCT_MOD_BY_LABEL = 12,
	ACTIVE_PLAYER_DYNAMIC_FIELD_TOYS = 13,
	ACTIVE_PLAYER_DYNAMIC_FIELD_TRANSMOG = 14
}
