namespace HermesProxy.World.Enums;

public enum AreaTriggerField
{
	AREATRIGGER_OVERRIDE_SCALE_CURVE = 0,
	AREATRIGGER_EXTRA_SCALE_CURVE = 1,
	AREATRIGGER_CASTER = 2,
	AREATRIGGER_DURATION = 3,
	AREATRIGGER_TIME_TO_TARGET = 4,
	AREATRIGGER_TIME_TO_TARGET_SCALE = 5,
	AREATRIGGER_TIME_TO_TARGET_EXTRA_SCALE = 6,
	AREATRIGGER_SPELLID = 7,
	AREATRIGGER_SPELL_FOR_VISUALS = 8,
	AREATRIGGER_SPELL_X_SPELL_VISUAL_ID = 9,
	AREATRIGGER_BOUNDS_RADIUS_2D = 10,
	AREATRIGGER_DECAL_PROPERTIES_ID = 11,
	AREATRIGGER_CREATING_EFFECT_GUID = 12,
	AREATRIGGER_END = 13
}
