namespace HermesProxy.World.Enums;

public enum AzeriteItemField
{
	AZERITE_ITEM_FIELD_XP = 0,
	AZERITE_ITEM_FIELD_LEVEL = 1,
	AZERITE_ITEM_FIELD_AURA_LEVEL = 2,
	AZERITE_ITEM_FIELD_KNOWLEDGE_LEVEL = 3,
	AZERITE_ITEM_FIELD_DEBUG_KNOWLEDGE_WEEK = 4,
	AZERITE_ITEM_END = 5
}
