namespace HermesProxy.World.Enums;

public enum ChatNotify
{
	Joined = 0,
	Left = 1,
	YouJoined = 2,
	YouLeft = 3,
	WrongPassword = 4,
	NotMember = 5,
	NotModerator = 6,
	PasswordChanged = 7,
	OwnerChanged = 8,
	PlayerNotFound = 9,
	NotOwner = 10,
	ChannelOwner = 11,
	ModeChange = 12,
	AnnouncementsOn = 13,
	AnnouncementsOff = 14,
	ModerationOn = 15,
	ModerationOff = 16,
	Muted = 17,
	PlayerKicked = 18,
	Banned = 19,
	PlayerBanned = 20,
	PlayerUnbanned = 21,
	PlayerNotBanned = 22,
	PlayerAlreadyMember = 23,
	Invite = 24,
	InviteWrongFaction = 25,
	WrongFaction = 26,
	InvalidName = 27,
	NotModerated = 28,
	PlayerInvited = 29,
	PlayerInviteBanned = 30,
	Throttled = 31,
	NotInArea = 32,
	NotInLfg = 33,
	VoiceOn = 34,
	VoiceOff = 35,
	TrialRestricted = 36,
	NotAllowedInChannel = 37
}
