namespace HermesProxy.World.Enums;

public enum ItemModifier
{
	TransmogAppearanceAllSpecs = 0,
	TransmogAppearanceSpec1 = 1,
	UpgradeId = 2,
	BattlePetSpeciesId = 3,
	BattlePetBreedData = 4,
	BattlePetLevel = 5,
	BattlePetDisplayId = 6,
	EnchantIllusionAllSpecs = 7,
	ArtifactAppearanceId = 8,
	TimewalkerLevel = 9,
	EnchantIllusionSpec1 = 10,
	TransmogAppearanceSpec2 = 11,
	EnchantIllusionSpec2 = 12,
	TransmogAppearanceSpec3 = 13,
	EnchantIllusionSpec3 = 14,
	TransmogAppearanceSpec4 = 15,
	EnchantIllusionSpec4 = 16,
	ChallengeMapChallengeModeId = 17,
	ChallengeKeystoneLevel = 18,
	ChallengeKeystoneAffixId1 = 19,
	ChallengeKeystoneAffixId2 = 20,
	ChallengeKeystoneAffixId3 = 21,
	ChallengeKeystoneAffixId4 = 22,
	ArtifactKnowledgeLevel = 23,
	ArtifactTier = 24,
	TransmogAppearanceSpec5 = 25,
	PvpRating = 26,
	EnchantIllusionSpec5 = 27,
	ContentTuningId = 28,
	ChangeModifiedCraftingStat1 = 29,
	ChangeModifiedCraftingStat2 = 30,
	TransmogSecondaryAppearanceAllSpecs = 31,
	TransmogSecondaryAppearanceSpec1 = 32,
	TransmogSecondaryAppearanceSpec2 = 33,
	TransmogSecondaryAppearanceSpec3 = 34,
	TransmogSecondaryAppearanceSpec4 = 35,
	TransmogSecondaryAppearanceSpec5 = 36,
	SoulbindConduitRank = 37,
	Max = 38
}
