namespace HermesProxy.World.Enums;

public enum PlayerDynamicField
{
	PLAYER_DYNAMIC_END = 0,
	PLAYER_DYNAMIC_FIELD_ARENA_COOLDOWNS = 1,
	PLAYER_DYNAMIC_FIELD_AVAILABLE_QUEST_LINE_X_QUEST_ID = 2,
	PLAYER_DYNAMIC_FIELD_CHARACTER_RESTRICTIONS = 3,
	PLAYER_DYNAMIC_FIELD_CONDITIONAL_TRANSMOG = 4,
	PLAYER_DYNAMIC_FIELD_DAILY_QUESTS = 5,
	PLAYER_DYNAMIC_FIELD_HEIRLOOM_FLAGS = 6,
	PLAYER_DYNAMIC_FIELD_HEIRLOOMS = 7,
	PLAYER_DYNAMIC_FIELD_RESEARCH_SITE_PROGRESS = 8,
	PLAYER_DYNAMIC_FIELD_RESERACH_SITE = 9,
	PLAYER_DYNAMIC_FIELD_SELF_RES_SPELLS = 10,
	PLAYER_DYNAMIC_FIELD_SPELL_FLAT_MOD_BY_LABEL = 11,
	PLAYER_DYNAMIC_FIELD_SPELL_PCT_MOD_BY_LABEL = 12,
	PLAYER_DYNAMIC_FIELD_TOYS = 13,
	PLAYER_DYNAMIC_FIELD_TRANSMOG = 14
}
