namespace HermesProxy.World.Enums;

public enum SceneObjectField
{
	SCENEOBJECT_FIELD_CREATEDBY = 0,
	SCENEOBJECT_FIELD_END = 1,
	SCENEOBJECT_FIELD_RND_SEED_VAL = 2,
	SCENEOBJECT_FIELD_SCENE_TYPE = 3,
	SCENEOBJECT_FIELD_SCRIPT_PACKAGE_ID = 4
}
