namespace HermesProxy.World.Enums;

public enum UnitField
{
	[UpdateField(UpdateFieldType.Int)]
	UNIT_CHANNEL_SPELL = 0,
	UNIT_CHANNEL_SPELL_X_SPELL_VISUAL = 1,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_CREATED_BY_SPELL = 2,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_DYNAMIC_FLAGS = 3,
	UNIT_END = 4,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_ATTACK_POWER = 5,
	[UpdateField(UpdateFieldType.Short)]
	UNIT_FIELD_ATTACK_POWER_MODS = 6,
	UNIT_FIELD_ATTACK_POWER_MOD_NEG = 7,
	UNIT_FIELD_ATTACK_POWER_MOD_POS = 8,
	[UpdateField(UpdateFieldType.Float)]
	UNIT_FIELD_ATTACK_POWER_MULTIPLIER = 9,
	UNIT_FIELD_ATTACK_SPEED_AURA = 10,
	[UpdateField(UpdateFieldType.Uint)]
	UNIT_FIELD_AURA = 11,
	[UpdateField(UpdateFieldType.Uint)]
	UNIT_FIELD_AURAFLAGS = 12,
	[UpdateField(UpdateFieldType.Bytes)]
	UNIT_FIELD_AURALEVELS = 13,
	[UpdateField(UpdateFieldType.Bytes)]
	UNIT_FIELD_AURAAPPLICATIONS = 14,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_AURASTATE = 15,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_BASEATTACKTIME = 16,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_BASE_HEALTH = 17,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_BASE_MANA = 18,
	UNIT_FIELD_BATTLEPET_COMPANION_NAME_TIMESTAMP = 19,
	UNIT_FIELD_BATTLE_PET_COMPANION_GUID = 20,
	UNIT_FIELD_BATTLE_PET_DB_ID = 21,
	UNIT_FIELD_BONUS_RESISTANCE_MODS = 22,
	[UpdateField(UpdateFieldType.Float)]
	UNIT_FIELD_BOUNDINGRADIUS = 23,
	[UpdateField(UpdateFieldType.Bytes)]
	UNIT_FIELD_BYTES_0 = 24,
	[UpdateField(UpdateFieldType.Bytes)]
	UNIT_FIELD_BYTES_1 = 25,
	[UpdateField(UpdateFieldType.Bytes)]
	UNIT_FIELD_BYTES_2 = 26,
	UNIT_FIELD_CHANNEL_DATA = 27,
	[UpdateField(UpdateFieldType.Guid)]
	UNIT_FIELD_CHANNEL_OBJECT = 28,
	UNIT_FIELD_CHARM = 29,
	[UpdateField(UpdateFieldType.Guid)]
	UNIT_FIELD_CHARMEDBY = 30,
	UNIT_FIELD_CONTENT_TUNING_ID = 31,
	[UpdateField(UpdateFieldType.Float)]
	UNIT_FIELD_COMBATREACH = 32,
	[UpdateField(UpdateFieldType.Guid)]
	UNIT_FIELD_CREATEDBY = 33,
	[UpdateField(UpdateFieldType.Guid)]
	UNIT_FIELD_CRITTER = 34,
	[UpdateField(UpdateFieldType.Guid)]
	UNIT_FIELD_DEMON_CREATOR = 35,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_DISPLAYID = 36,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_DISPLAY_POWER = 37,
	UNIT_FIELD_DISPLAY_SCALE = 38,
	UNIT_FIELD_EFFECTIVE_LEVEL = 39,
	UNIT_FIELD_END = 40,
	[UpdateField(UpdateFieldType.Custom)]
	UNIT_FIELD_FACTIONTEMPLATE = 41,
	[UpdateField(UpdateFieldType.Uint)]
	UNIT_FIELD_FLAGS = 42,
	[UpdateField(UpdateFieldType.Uint)]
	UNIT_FIELD_FLAGS_2 = 43,
	[UpdateField(UpdateFieldType.Uint)]
	UNIT_FIELD_FLAGS_3 = 44,
	UNIT_FIELD_GUILD_GUID = 45,
	[UpdateField(UpdateFieldType.Uint)]
	UNIT_FIELD_HEALTH = 46,
	[UpdateField(UpdateFieldType.Float)]
	UNIT_FIELD_HOVERHEIGHT = 47,
	UNIT_FIELD_INTERACT_SPELLID = 48,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_LEVEL = 49,
	UNIT_FIELD_LOOKS_LIKE_CREATURE_ID = 50,
	UNIT_FIELD_LOOKS_LIKE_MOUNT_ID = 51,
	UNIT_FIELD_LOOK_AT_CONTROLLER_ID = 52,
	UNIT_FIELD_LOOK_AT_CONTROLLER_TARGET = 53,
	UNIT_FIELD_LIFESTEAL = 54,
	UNIT_FIELD_MAIN_HAND_WEAPON_ATTACK_POWER = 55,
	UNIT_FIELD_MAXDAMAGE = 56,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_MAXHEALTH = 57,
	UNIT_FIELD_MAXHEALTHMODIFIER = 58,
	UNIT_FIELD_MAXITEMLEVEL = 59,
	UNIT_FIELD_MAXOFFHANDDAMAGE = 60,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_MAXPOWER = 61,
	UNIT_FIELD_MAXPOWER1 = 62,
	UNIT_FIELD_MAXPOWER10 = 63,
	UNIT_FIELD_MAXPOWER11 = 64,
	UNIT_FIELD_MAXPOWER2 = 65,
	UNIT_FIELD_MAXPOWER3 = 66,
	UNIT_FIELD_MAXPOWER4 = 67,
	UNIT_FIELD_MAXPOWER5 = 68,
	UNIT_FIELD_MAXPOWER6 = 69,
	UNIT_FIELD_MAXPOWER7 = 70,
	UNIT_FIELD_MAXPOWER8 = 71,
	UNIT_FIELD_MAXPOWER9 = 72,
	UNIT_FIELD_MAXRANGEDDAMAGE = 73,
	UNIT_FIELD_MINDAMAGE = 74,
	UNIT_FIELD_MINOFFHANDDAMAGE = 75,
	UNIT_FIELD_MINRANGEDDAMAGE = 76,
	UNIT_FIELD_MIN_ITEM_LEVEL = 77,
	UNIT_FIELD_MIN_ITEM_LEVEL_CUTOFF = 78,
	UNIT_FIELD_MOD_BONUS_ARMOR = 79,
	[UpdateField(UpdateFieldType.Float)]
	UNIT_FIELD_MOD_HASTE = 80,
	[UpdateField(UpdateFieldType.Float)]
	UNIT_FIELD_MOD_HASTE_REGEN = 81,
	[UpdateField(UpdateFieldType.Float)]
	UNIT_FIELD_MOD_RANGED_HASTE = 82,
	[UpdateField(UpdateFieldType.Float)]
	UNIT_FIELD_MOD_TIME_RATE = 83,
	[UpdateField(UpdateFieldType.Uint)]
	UNIT_FIELD_MOUNTDISPLAYID = 84,
	[UpdateField(UpdateFieldType.Uint)]
	UNIT_FIELD_NATIVEDISPLAYID = 85,
	UNIT_FIELD_NATIVE_X_DISPLAY_SCALE = 86,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_NEGSTAT = 87,
	UNIT_FIELD_NEGSTAT0 = 88,
	UNIT_FIELD_NEGSTAT1 = 89,
	UNIT_FIELD_NEGSTAT2 = 90,
	UNIT_FIELD_NEGSTAT3 = 91,
	UNIT_FIELD_NEGSTAT4 = 92,
	UNIT_FIELD_OFF_HAND_WEAPON_ATTACK_POWER = 93,
	UNIT_FIELD_OVERRIDE_DISPLAY_POWER_ID = 94,
	UNIT_FIELD_PADDING = 95,
	UNIT_FIELD_PETEXPERIENCE = 96,
	UNIT_FIELD_PETNEXTLEVELEXP = 97,
	UNIT_FIELD_PETNUMBER = 98,
	UNIT_FIELD_PET_NAME_TIMESTAMP = 99,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_POSSTAT = 100,
	UNIT_FIELD_POSSTAT0 = 101,
	UNIT_FIELD_POSSTAT1 = 102,
	UNIT_FIELD_POSSTAT2 = 103,
	UNIT_FIELD_POSSTAT3 = 104,
	UNIT_FIELD_POSSTAT4 = 105,
	UNIT_FIELD_POWER = 106,
	UNIT_FIELD_POWER1 = 107,
	UNIT_FIELD_POWER10 = 108,
	UNIT_FIELD_POWER11 = 109,
	UNIT_FIELD_POWER2 = 110,
	UNIT_FIELD_POWER3 = 111,
	UNIT_FIELD_POWER4 = 112,
	UNIT_FIELD_POWER5 = 113,
	UNIT_FIELD_POWER6 = 114,
	UNIT_FIELD_POWER7 = 115,
	UNIT_FIELD_POWER8 = 116,
	UNIT_FIELD_POWER9 = 117,
	UNIT_FIELD_POWER_COST_MODIFIER = 118,
	UNIT_FIELD_POWER_COST_MULTIPLIER = 119,
	UNIT_FIELD_POWER_COST_MULTIPLIER1 = 120,
	UNIT_FIELD_POWER_COST_MULTIPLIER2 = 121,
	UNIT_FIELD_POWER_COST_MULTIPLIER3 = 122,
	UNIT_FIELD_POWER_COST_MULTIPLIER4 = 123,
	UNIT_FIELD_POWER_COST_MULTIPLIER5 = 124,
	UNIT_FIELD_POWER_COST_MULTIPLIER6 = 125,
	UNIT_FIELD_POWER_COST_MULTIPLIER7 = 126,
	UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER = 127,
	UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER = 128,
	UNIT_FIELD_RANGEDATTACKTIME = 129,
	UNIT_FIELD_RANGED_ATTACK_POWER = 130,
	[UpdateField(UpdateFieldType.Short)]
	UNIT_FIELD_RANGED_ATTACK_POWER_MODS = 131,
	UNIT_FIELD_RANGED_ATTACK_POWER_MOD_NEG = 132,
	UNIT_FIELD_RANGED_ATTACK_POWER_MOD_POS = 133,
	UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER = 134,
	UNIT_FIELD_RANGED_HAND_WEAPON_ATTACK_POWER = 135,
	UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE = 136,
	UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE_ARCANE = 137,
	UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE_ARMOR = 138,
	UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE_FIRE = 139,
	UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE_FROST = 140,
	UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE_HOLY = 141,
	UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE_NATURE = 142,
	UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE_SHADOW = 143,
	UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE = 144,
	UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE_ARCANE = 145,
	UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE_ARMOR = 146,
	UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE_FIRE = 147,
	UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE_FROST = 148,
	UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE_HOLY = 149,
	UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE_NATURE = 150,
	UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE_SHADOW = 151,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_RESISTANCES = 152,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_RESISTANCES_ARCANE = 153,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_RESISTANCES_ARMOR = 154,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_RESISTANCES_FIRE = 155,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_RESISTANCES_FROST = 156,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_RESISTANCES_HOLY = 157,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_RESISTANCES_NATURE = 158,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_RESISTANCES_SHADOW = 159,
	UNIT_FIELD_SANDBOX_SCALING_ID = 160,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_SCALE_DURATION = 161,
	UNIT_FIELD_SCALING_DAMAGE_ITEM_LEVEL_CURVE_ID = 162,
	UNIT_FIELD_SCALING_FACTION_GROUP = 163,
	UNIT_FIELD_SCALING_HEALTH_ITEM_LEVEL_CURVE_ID = 164,
	UNIT_FIELD_SCALING_LEVEL_MIN = 165,
	UNIT_FIELD_SCALING_LEVEL_MAX = 166,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_SCALING_LEVEL_DELTA = 167,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_STAT = 168,
	UNIT_FIELD_STAT0 = 169,
	UNIT_FIELD_STAT1 = 170,
	UNIT_FIELD_STAT2 = 171,
	UNIT_FIELD_STAT3 = 172,
	UNIT_FIELD_STAT4 = 173,
	UNIT_FIELD_STATE_ANIM_ID = 174,
	UNIT_FIELD_STATE_ANIM_KIT_ID = 175,
	UNIT_FIELD_STATE_SPELL_VISUAL_ID = 176,
	UNIT_FIELD_STATE_WORLD_EFFECT_ID = 177,
	UNIT_FIELD_SUMMON = 178,
	[UpdateField(UpdateFieldType.Guid)]
	UNIT_FIELD_SUMMONEDBY = 179,
	UNIT_FIELD_SUMMONED_BY_HOME_REALM = 180,
	[UpdateField(UpdateFieldType.Guid)]
	UNIT_FIELD_TARGET = 181,
	UNIT_TRAINING_POINTS = 182,
	UNIT_FIELD_UNK63 = 183,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_FIELD_WILD_BATTLEPET_LEVEL = 184,
	[UpdateField(UpdateFieldType.Float)]
	UNIT_MOD_CAST_HASTE = 185,
	[UpdateField(UpdateFieldType.Float)]
	UNIT_MOD_CAST_SPEED = 186,
	[UpdateField(UpdateFieldType.Int)]
	UNIT_NPC_EMOTESTATE = 187,
	[UpdateField(UpdateFieldType.Uint)]
	UNIT_NPC_FLAGS = 188,
	[UpdateField(UpdateFieldType.Uint)]
	UNIT_VIRTUAL_ITEM_SLOT_ID = 189,
	[UpdateField(UpdateFieldType.Uint)]
	UNIT_VIRTUAL_ITEM_SLOT_DISPLAY = 190
}
