namespace HermesProxy.World.Enums;

public enum UnitDynamicField
{
	UNIT_DYNAMIC_FIELD_CHANNEL_OBJECTS = 0,
	UNIT_DYNAMIC_FIELD_PASSIVE_SPELLS = 1,
	UNIT_DYNAMIC_FIELD_WORLD_EFFECTS = 2,
	UNIT_DYNAMIC_END = 3
}
