namespace HermesProxy.World.Enums.V3_4_3_54261;

public enum CorpseField
{
	CORPSE_FIELD_OWNER = 7,
	CORPSE_FIELD_PARTY_GUID = 11,
	CORPSE_FIELD_GUILD_GUID = 15,
	CORPSE_FIELD_DISPLAY_ID = 19,
	CORPSE_FIELD_ITEMS = 20,
	CORPSE_FIELD_BYTES_1 = 39,
	CORPSE_FIELD_FLAGS = 40,
	CORPSE_FIELD_DYNAMIC_FLAGS = 41,
	CORPSE_FIELD_FACTION_TEMPLATE = 42,
	CORPSE_FIELD_CUSTOMIZATION_CHOICES = 43,
	CORPSE_END = 113
}
