namespace HermesProxy.World.Enums.V3_4_3_54261;

public enum ItemDynamicField
{
	ITEM_DYNAMIC_FIELD_MODIFIERS = 0,
	ITEM_DYNAMIC_FIELD_BONUSLIST_IDS = 1,
	ITEM_DYNAMIC_FIELD_ARTIFACT_POWERS = 2,
	ITEM_DYNAMIC_FIELD_GEMS = 3,
	ITEM_DYNAMIC_END = 4
}
