namespace HermesProxy.World.Enums.V3_4_3_54261;

public enum SceneObjectField
{
	SCENEOBJECT_FIELD_SCRIPT_PACKAGE_ID = 7,
	SCENEOBJECT_FIELD_RND_SEED_VAL = 8,
	SCENEOBJECT_FIELD_CREATEDBY = 9,
	SCENEOBJECT_FIELD_SCENE_TYPE = 13,
	SCENEOBJECT_END = 14
}
