namespace HermesProxy.World.Enums.V3_4_3_54261;

public enum UnitDynamicField
{
	UNIT_DYNAMIC_FIELD_PASSIVE_SPELLS = 0,
	UNIT_DYNAMIC_FIELD_WORLD_EFFECTS = 1,
	UNIT_DYNAMIC_FIELD_CHANNEL_OBJECTS = 2,
	UNIT_DYNAMIC_END = 3
}
